<?php

namespace ContainerW91vXQc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rrw13pkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rrw13pk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rrw13pk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'referentiel' => ['privates', 'App\\Repository\\ReferentielsRepository', 'getReferentielsRepositoryService', true],
        ], [
            'referentiel' => 'App\\Repository\\ReferentielsRepository',
        ]);
    }
}
