<?php

namespace ContainerW91vXQc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VEl0X4tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vEl0X4t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vEl0X4t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'helperUser' => ['privates', 'App\\Helper\\UserHelper', 'getUserHelperService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'helperUser' => 'App\\Helper\\UserHelper',
            'serializer' => '?',
        ]);
    }
}
