<?php

namespace ContainerW91vXQc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeCompetencesCollectionDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\GroupeCompetencesCollectionDataProvider' shared autowired service.
     *
     * @return \App\DataProvider\GroupeCompetencesCollectionDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/GroupeCompetencesCollectionDataProvider.php';

        return $container->privates['App\\DataProvider\\GroupeCompetencesCollectionDataProvider'] = new \App\DataProvider\GroupeCompetencesCollectionDataProvider(($container->privates['App\\Repository\\CompetenceRepository'] ?? $container->load('getCompetenceRepositoryService')));
    }
}
