<?php

namespace ContainerW91vXQc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilSortieControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProfilSortieController' shared autowired service.
     *
     * @return \App\Controller\ProfilSortieController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProfilSortieController.php';

        $container->services['App\\Controller\\ProfilSortieController'] = $instance = new \App\Controller\ProfilSortieController(($container->privates['App\\Repository\\PromosRepository'] ?? $container->load('getPromosRepositoryService')), ($container->privates['App\\Repository\\ApprenantRepository'] ?? $container->load('getApprenantRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ProfilSortieController', $container));

        return $instance;
    }
}
