<?php

namespace ContainerW91vXQc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagsCollectionDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\TagsCollectionDataProvider' shared autowired service.
     *
     * @return \App\DataProvider\TagsCollectionDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/TagsCollectionDataProvider.php';

        return $container->privates['App\\DataProvider\\TagsCollectionDataProvider'] = new \App\DataProvider\TagsCollectionDataProvider(($container->privates['App\\Repository\\TagsRepository'] ?? $container->load('getTagsRepositoryService')));
    }
}
