<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW91vXQc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW91vXQc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW91vXQc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW91vXQc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW91vXQc\App_KernelDevDebugContainer([
    'container.build_hash' => 'W91vXQc',
    'container.build_id' => '4c11af06',
    'container.build_time' => 1613483399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW91vXQc');
